// Generated by CoffeeScript 1.4.0
(function() {
  var EventEmitter, Mumail, fs, hogan, nodemailer, path,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  nodemailer = require('nodemailer');

  fs = require('fs');

  path = require('path');

  hogan = require('hogan.js');

  EventEmitter = require('events').EventEmitter;

  Mumail = (function(_super) {
    var cachedTemplates;

    __extends(Mumail, _super);

    cachedTemplates = {};

    function Mumail(_arg) {
      this.templatePath = _arg.templatePath, this.from = _arg.from;
      this.transport = nodemailer.createTransport('sendmail');
    }

    Mumail.prototype.send = function(_arg) {
      var data, from, htmlPath, opts, subject, template, textPath, to,
        _this = this;
      from = _arg.from, to = _arg.to, subject = _arg.subject, template = _arg.template, data = _arg.data;
      from = from != null ? from : this.from;
      htmlPath = path.join(this.templatePath, "" + template + ".html");
      textPath = path.join(this.templatePath, "" + template + ".txt");
      opts = {
        from: from,
        to: to,
        subject: subject
      };
      if (__indexOf.call(cachedTemplates, htmlPath) >= 0) {
        return this.renderAndSend(opts, cachedTemplates[htmlPath], data);
      } else {
        return fs.readFile(htmlPath, 'utf-8', function(err, html) {
          cachedTemplates[htmlPath] = hogan.compile(html);
          return _this.renderAndSend(opts, cachedTemplates[htmlPath], data);
        });
      }
    };

    Mumail.prototype.renderAndSend = function(opts, template, data) {
      var _this = this;
      opts.html = template.render(data);
      return this.transport.sendMail(opts, function(error, response) {
        if (error) {
          return _this.emit('error', error);
        } else {
          return _this.emit('done', response);
        }
      });
    };

    return Mumail;

  })(EventEmitter);

  module.exports = Mumail;

}).call(this);
